### ISSUE TITLE
unarchive vscode-show-unsaved-changes 

### ISSUE THREAD

**Issue by psultan** [ctf0/vscode-php-class-generator#1]
This issue is actually just to mention I think you should unarchive your vscode-show-unsaved-changes.  (I cannot leave an issue on that project since it is archived).  Vscode's Local History(March 2022) update does not show unsaved changes in the gutter like your extension does.  If you look closely on their gif demo the gutter indicators only appear because their file is under version control (not from local history).  In fact their last request to do so (https://github.com/microsoft/vscode/issues/146626) was recently closed due to their upvoting system.  

Luckily, your vscode-show-unsaved-changes still seems to be functioning in the latest vscode builds.  But it is a shame it is marked as archived because it is still useful with no other alternatives.

**Comment by ctf0** [comment]
thank u for reaching out, it's now alive again.
