### ISSUE TITLE
Renaming a class file name replaces more than just the class reference

### ISSUE THREAD

**Issue by kapersoft** [ctf0/vscode-php-class-generator#3]
Hi,

I found another issue. When I do the following:
- Install an empty Laravel project using `larvae new testing`
- Open the project in VSCode
- Rename `app/Models/User.php ` to `app/Models/Person.php`
- Your plugin renames every `User` to `Person` in all files, also when it doesn't point to the `App\Models\Person`-class

For example:
- In `config/auth.php` on line 47, in the docblock the text `User Providers` is replaced by `Person Providers`.
- In `database/factories/UserFactory.php` on line 11, the classname is updated to `PersonFactory`, while the filename is not updated and is still classed `UserFactory.php`.
- In `database/seeders/DatabaseSeeder.php` commented code with a reference to `\App\Models\User` is updated.
- In `routes/channels.php` the string `'App.Models.User.{id}'` is updated to `'App.Models.Person.{id}'`
- etc...

I also tested this in a large project, and it replaced a lot more than it should, like renaming classnames of controllers/Jobs/etc. without renaming the file, updating string, updating comments, etc.

Imho it should only rename not commented code referencing to renamed class/file. In this case `App\Models\User` to `App\Models\Person` and not all texts containing `User` to `Person`.

Is that feasible in VSCode? Or are we stuck with simple text replacement? It would be unfortunate if a developer must undo every unwanted change after renaming a class/file.

**Comment by ctf0** [comment]
oh, sorry for that.

the problem is, i can easily change the namespace but what about the class it self ?, in this case i have 3 solutions
- rename anything refrence the old class name "the current"
- add the old classname to the namespace as alias "i think this is kinda better"
- wait until https://github.com/microsoft/vscode/issues/168825 is fixed and rely on class references instead to make the changes check https://github.com/ctf0/vscode-php-class-generator/compare/main...symbol-api

**Comment by ctf0** [comment]
for now i will go with the second solution, as its far more safer than the current solution, 
when the 3rd solution is finalized i will try to use it instead but sadly it will add more restriction on how the ext works.

plz retest with the new ext update once its published and reply back if the issue still persists, thanks again for ur help.

**Comment by ctf0** [comment]
the second solution is now an opt-in config `phpClassGenerator.setNamespaceToAlias: false`
